spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: sa
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
